name: ci-deploying
run-name: ${{ github.actor }} is deploying GreenRute frontend release
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install all dependencies
        run: |
          corepack enable yarn
          yarn install --frozen-lockfile

      - name: Build
        run: yarn generate

      - name: Add CNAME
        run: |
          cd .output/public
          echo "beta.greenrute.com" > CNAME
          cd ..

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: .output/public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Розгортання: ({sha}) {msg}"
